### ISSUE TITLE
Course completion

### ISSUE THREAD

**Issue by pnbowen** [Kylegoslin/moodle-block_cmanager#106]
All courses created using cmanager seem to have course completion set to no. This should be either a choice, or at least set to what the moodle course default is.

I have tested adding the line to cmanager\lib\course_lib.php
	$new_course->enablecompletion = get_config('moodlecourse','enablecompletion');

This pulls the default setting, and seems to work without issue. I would recommend it be placed in the code.

**Comment by danielmcsweeney** [comment]
Done. Thanks
