### ISSUE TITLE
Module directory structure

### ISSUE THREAD

**Issue by dkleto** [Kylegoslin/moodle-block_cmanager#112]
The current directory structure with all of the module code residing inside the "cmanager" directory is a bit unusual for a Moodle plugin, and breaks a few specific use-cases.

Cloning the module directly into a Moodle codebase results in a broken installation, as Moodle looks for a version.php in the root directory of the module. This is significant for administrators using git submodules to maintain their 3rd party modules, as it prevents them from installing an unaltered version of the plugin.

It would be great if cmanager could be rearranged a bit with version.php etc. in the root directory of the module.

Thanks!

**Comment by danielmcsweeney** [comment]
Hi
apologies that was my error. I wasn't sure if GIT representations of blocks needed to be in a directory with the exact block name (as per the upload zips)
Hope this resolves it
Daniel

**Comment by dkleto** [comment]
Great! That works for me. Thanks for being so quick to respond.
