### ISSUE TITLE
Blocks move to footer

### ISSUE THREAD

**Issue by Apex-Oil** [Kylegoslin/moodle-block_cmanager#113]
Moodle Version: 2.8.6+ (Build: 20150702)
Plugin Version: 2015052543

When working in the manager non of the blocks (navigation, Administration, etc) are displayed on the right or he left.  They are moved to the footer and I can move them left to right.

When I use one of the basic the themes I see that there are no blocks when working in the manger.  So the block showing up might be a theme thing.

Might it be possible to keep the standard block when working with the manger?  Such as Navigation.

I have attached a image to better show what I am seeing.
![existing_requests](https://cloud.githubusercontent.com/assets/10236753/9087794/18f50062-3b4a-11e5-9d28-5575eef0490f.PNG)

Thanks.

**Comment by danielmcsweeney** [comment]
To be honest this looks like a theme issue. The cmanager block does not look to load the nav blocks etc on the admin pages. What theme are you using?
