### ISSUE TITLE
Plugin block_cmanager does not declare valid $plugin->component in its version.php.

### ISSUE THREAD

**Issue by nitro2010** [Kylegoslin/moodle-block_cmanager#114]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Plugin block_cmanager does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 442 of /lib/classes/update/checker.php: call to core_plugin_manager->get_plugins()
line 459 of /lib/classes/update/checker.php: call to core\update\checker->load_current_environment()
line 239 of /lib/classes/update/checker.php: call to core\update\checker->prepare_request_params()
line 124 of /lib/classes/update/checker.php: call to core\update\checker->get_response()
line 542 of /admin/index.php: call to core\update\checker->fetch()

**Comment by sashkashurik** [comment]
Add:
$plugin->component = 'block_cmanager'; in version.php and it will fix all install issues. However, the block still needs to be tested under 3.0

**Comment by nitro2010** [comment]
it fix in https://github.com/Kylegoslin/moodle-block_cmanager/pull/115

**Comment by Kylegoslin** [comment]
Added to new release, thanks all.
