### ISSUE TITLE
Debug error when installing using install Add-ons

### ISSUE THREAD

**Issue by MarkWhitington** [Kylegoslin/moodle-block_cmanager#84]
I had debugging on when installing Course Request Manager and the following appeared...
![image](https://f.cloud.github.com/assets/7004621/2467127/8122ef6e-afb9-11e3-8801-37011a5190d4.png)

 I had previously added Certificate; Simple Certificate; Face-to-face...
After Course Request Manager installed I get the following Debug Error whilst trying to access the Site Administration link...
![image](https://f.cloud.github.com/assets/7004621/2467161/cd3e715c-afb9-11e3-8e50-75dc506673b9.png)

This error prevents me from accessing/using Site Administration.
Is there something I am missing?
Thanks in advance.

**Comment by danielmcsweeney** [comment]
Unable to replicate
